### PR TITLE
Feature: speaker rotation

### PR DESCRIPTION
**Pull request by alexlande**
This adds a quick random speaker display to the homepage. Picks a random speaker for each day + displays them. All of the speakers are in the page HTML but are hidden by default.

/cc @davethegr8 @crtr0

### CODE REVIEW

**Comment by alexlande** [comment]
Ugh, forgot about images. They're all getting downloaded. Hold off on merging this, will fix.

**Comment by alexlande** [comment]
Ok, added lazy loading for the homepage speaker images so only the active one is loaded.

**Comment by davethegr8** [comment]
I'm curious - for you, what's the pros and cons to putting all the content in the document and showing one vs filling in data from a json file?

**Comment by alexlande** [comment]
Based the decision entirely on simplicity. If we built them dynamically, you've got to do string concatenation or front-end templating, then you've got to keep that in sync with the backend template we're using, since they wouldn't be shared.

With this method the document size is slightly larger than the other way, but it should gzip really well so it shouldn't be a real issue.

**Comment by davethegr8** [comment]
Fair enough, sounds like a reasonable solution. Thanks!

**Pull request merged**
