### PR TITLE
setting up layout demo to play with on cascadiacss day

### PR DESCRIPTION
**Pull request by zachattack**
I am currently working on some placement ideas for the sponsors and a couple more tweaks but this is the bulk of the demo info.

### CODE REVIEW

**Comment by davethegr8** [comment]
Can you post a screen shot of it working in action? I use http://www.s3blog.org/screengrab.html in firefox for taking screenshots.

**Comment by zachattack** [comment]
cascadiafest-css-2015

**Comment by davethegr8** [comment]
It looks like the header nav is using a faux-bold weight, can we change that?

Per earlier convos in slack, I'd like to change:

* sponsors need WAY more love. whole row below speakers and above staff.
* similar sponsor treatment as http://2012.cascadiajs.com/, such as "schedule - track day sponsor CMYK" or "Lunch provided by RGB"
* We won't have a need for the schedule until closer to the conf, so that should drop out for now

Also since surge/harp will compile ejs templates into html, I'd like to use the `_data.json` file option to build page. Doesn't have to be right away, but soon.

**Comment by zachattack** [comment]
cascadiafest-css-2015-ver02

**Comment by zachattack** [comment]
Updated image for to give example of glorious sponsor logo options :)

**Comment by davethegr8** [comment]
:+1:

**Pull request merged**
